trigger:
  name: On Push to main
  identifier: on_push_main
  enabled: true
  description: Run on push to main branch
  tags: {}
  orgIdentifier: acme_corp
  projectIdentifier: platform_services
  pipelineIdentifier: ollama_demo
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: github
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
          headerConditions: []
          repoName: harness-demo
          actions: []
  inputYaml: |
    pipeline:
      identifier: ollama_demo
      properties:
        ci:
          codebase:
            build:
              type: branch
              spec:
                branch: <+trigger.branch>
